version: '3.3'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loc_authority_tools
    ports:
      - "5434:5434"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -p 5434
volumes:
  db-data:
